### ISSUE TITLE
🚀 EPIC Create package `eyewit`

### ISSUE THREAD

**Issue by kalaschnik** [ccp-eva/eyewit#19]
Seems to be the better approach instead of sourcing
https://community.rstudio.com/t/how-to-manage-multiple-user-defined-functions/16246/3

However, maybe this plays not so nice with shiny?

more good reads in dependency mgmt (using `packrat`)
- https://blog.learningtree.com/manage-packages-in-r-how/
- https://www.r-bloggers.com/%F0%9F%93%A6-managing-dependencies-in-packages/

**Comment by Kalaschnik** [comment]
#### Read this: https://r-pkgs.org/index.html

**Comment by kalaschnik** [comment]
Done with 41d10a44bac650c3c48f8e0bb5b2c02488ca9119

Package dev happend with devtools and usethis, roxygen2 et al
